version: '3.7'

services:

  web:
    build:
      context: https://github.com/Superdanby/faq-django-postgres-gunicorn-nginx.git
      dockerfile: dockerfile
    restart: always
    working_dir: /faq-django-postgres-gunicorn-nginx
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && gunicorn faq.wsgi -b 0.0.0.0:8181"
    volumes:
      - ./media:/media
      - ./static:/static
    env_file:
        - .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    env_file:
        - .env
    ports:
      - "8111:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data:Z"

  nginx:
    build:
      context: https://github.com/Superdanby/faq-django-postgres-gunicorn-nginx.git
      dockerfile: nginx.dockerfile
    volumes:
      - ./media:/media
      - ./static:/static
    restart: always
    ports:
      - 80:80
    depends_on:
      - web
